version: "3.9"
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    volumes:
      - ./data:/data
    command: >
      osrm-routed
      --algorithm mld
      /data/lucknow.osrm
    ports:
      - "5000:5000"
